Upload exe Day6
tuyenbq97-edsolabs/Edsolabs-Frontend-Training pull request #19
Opened 2022-03-22 09:28 UTC by QuanLe801

![image](https://user-images.githubusercontent.com/101615102/159449096-6930b57f-9fcf-4d0e-9aaa-899551d076ee.png)

2022-03-22 09:32 UTC, tuyenbq97-edsolabs requested changes

2022-03-22 09:32 UTC, tuyenbq97-edsolabs commented on Day6/QuanLM/style.css
> +.form-control_title{
duplicate style

2022-03-22 09:32 UTC, tuyenbq97-edsolabs commented on Day6/QuanLM/style.css
> +.control-group img{
duplicate style

2022-03-22 09:32 UTC, tuyenbq97-edsolabs commented on Day6/QuanLM/style.css
> +.btn_other-submit{
hạn chế set width

2022-03-22 09:32 UTC, tuyenbq97-edsolabs commented
Check lại font family cho anh nhé

2022-03-22 10:01 UTC, tuyenbq97-edsolabs commented
![image](https://user-images.githubusercontent.com/101078482/159455570-dbc2f901-9ec3-4543-8c5b-464640a7be93.png)
Phần này đang cần blur nhé e

2022-03-22 11:39 UTC, QuanLe801 commented
Phần đó có blur cho max-width 414 px a ơi. Tại màn hình nếu trên 414 thì e
bỏ blur chỗ đó vì k biết design như nào cho hợp lí. A check lại giúp e nha

Vào Th 3, 22 thg 3, 2022 lúc 17:01 Bùi Quang Tuyền ***@***.***>
đã viết:

> [image: image]
> <https://user-images.githubusercontent.com/101078482/159455570-dbc2f901-9ec3-4543-8c5b-464640a7be93.png>
> Phần này đang cần blur nhé e
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tuyenbq97-edsolabs/Edsolabs-Frontend-Training/pull/19#issuecomment-1074971177>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYHIL7RKZQT2EEC66NWZ4Z3VBGK6RANCNFSM5RKIG7DQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***
> com>
>

2022-03-23 02:36 UTC, tuyenbq97-edsolabs commented
bỏ blur thì em dùng responsive nhé, chứ không set width

2022-03-28 06:57 UTC, merged