upload exe day 7
tuyenbq97-edsolabs/Edsolabs-Frontend-Training pull request #21
Opened 2022-04-06 06:59 UTC by QuanLe801

2022-04-06 07:03 UTC, tuyenbq97-edsolabs approved these changes

2022-04-06 07:03 UTC, tuyenbq97-edsolabs commented on Day7_js/QuanLM/exe3.html
> +        console.log(isEmpty(null));
em test với case này: isEmpty('hello world'); => false
isEmpty(1); => true

2022-04-06 07:21 UTC, QuanLe801 commented on Day7_js/QuanLM/exe3.html
> +        console.log(isEmpty(null));
isEmpty(1); thì đúng true a ạ. Nhưng isEmpty('hello world'); của e đang true vì e chưa có ktra điều kiện length != 0 a ạ. e sẽ fix lại

2022-04-06 08:32 UTC, tuyenbq97-edsolabs requested changes

2022-04-06 08:32 UTC, tuyenbq97-edsolabs commented on Day7_js/QuanLM/exe5.html
> +        different([1,2,4,5,3] , [2,3,8]);
em thử suy nghĩ theo hướng khác xem, không dùng loop nữa, dùng includes thử xem ?

2022-04-13 10:38 UTC, BangPv1202 commented on Day7+/QuanLM/exe.html
> +        function isEmpty(){
tách ra 1 file js, xong em import js vào nhé

2022-04-13 10:40 UTC, QuanLe801 commented on Day7+/QuanLM/exe.html
> +        function isEmpty(){
vâng ạ

2022-05-25 05:07 UTC, closed without merging